import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import { Inter } from "@next/font/google";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { SiDiscord } from "react-icons/si";
import Image from "next/image";
import avatar from "../public/dev-ed-wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import download from "./download";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Template portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white text-black px-10 dark:bg-gray-900 dark:text-white">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons mr-0">developedByAtharv</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                    console.log("clicked");
                  }}
                  className="cursor-pointer text-2xl ml-4"
                />
              </li>
              <li>
                <a
                  onClick={download}
                  className="bg-gradient-to-r from-cyan-500 to-blue-400 px-4 py-2 ml-8 rounded-xl cursor-pointer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-3xl text-teal-500 py-2 md:text-5xl">
              Atharv Kumar
            </h2>
            <h3 className="text-xl py-2 md:text-2xl">Developer & Designer</h3>
            <p className="text-sm py-5 text-gray-800 md:text-xl dark:text-white">
              Am a developer for fun and create stuffs by referring youtube and
              internet ChatGPT is there to kill all the creative/coding works
              and soon there will be no jobs for us i don't know what will you
              do .. Cause my future am building on brute patience and steadiness
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-gray-700">
            <a href="https://discord.com/channels/@me">
              <SiDiscord className="cursor-pointer dark:text-white" />
            </a>
            <a href="https://www.linkedin.com/in/rajesh-kumar-behera-090a33219">
              <AiFillLinkedin className="cursor-pointer dark:text-white" />
            </a>
            <a href="https://github.com/Rajesh01-star">
              <AiFillGithub className="cursor-pointer dark:text-white" />
            </a>
          </div>
          <div className="relative overflow-hidden bg-gradient-to-b from-teal-500 mx-auto mt-20 rounded-full w-80 h-80 mb-10">
            <Image
              alt="avatar element"
              src={avatar}
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>

        {/* section 2 */}
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I offer</h3>
            <p className="text-lg py-2 text-gray-800 leading-8 inline dark:text-white">
              Since I am a web developer I am fluent in
              HTML,CSS,Javascript,React,NodeJs,MongoDB. I have done internships
              at and Microsoft inc. and have been on a post of
              assistant-developer at{" "}
              <span className="text-cyan-500">Google</span> also
            </p>
            <p className="text-lg py-2 text-gray-800 leading-8 inline dark:text-white">
              leveling up my skills inch by inch is my goal and am never
              satisfied this is my{" "}
              <span className="text-cyan-500">resolve</span>.
            </p>
          </div>
          <div className="lg:flex justify-center gap-5">
            {/* design */}
            <div className="bg-slate-200 text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800 ">
              <div className="flex justify-center">
                <Image
                  alt="Design element"
                  src={design}
                  height={100}
                  width={100}
                />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p>
                Creating elegant designs with perfections with the history
                relative
              </p>
              <h4 className="text-xl text-teal-600 py-4">
                Designs tools I used
              </h4>
              <p className="text-gray-800 dark:text-white ">Illustrator</p>
              <p className="text-gray-800 dark:text-white">Figma</p>
              <p className="text-gray-800 dark:text-white">Blender</p>
              <p className="text-gray-800 dark:text-white">Splice.com</p>
            </div>
            {/* code */}
            <div className="bg-slate-200 text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800">
              <div className="flex justify-center">
                <Image alt="code element" src={code} height={100} width={100} />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p>
                Creating elegant designs with perfections with the history
                relative
              </p>
              <h4 className="text-xl text-teal-600 py-4">
                Designs tools I used
              </h4>
              <p className="text-gray-800 dark:text-white ">Illustrator</p>
              <p className="text-gray-800 dark:text-white">Figma</p>
              <p className="text-gray-800 dark:text-white">Blender</p>
              <p className="text-gray-800 dark:text-white">Splice.com</p>
            </div>
            {/* consulting */}
            <div className="bg-slate-200 text-center shadow-xl p-10 rounded-xl my-10 dark:bg-gray-800">
              <div className="flex justify-center">
                <Image
                  alt="consulting element"
                  src={consulting}
                  height={100}
                  width={100}
                />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">
                Beautiful designs
              </h3>
              <p>
                Creating elegant designs with perfections with the history
                relative
              </p>
              <h4 className="text-xl text-teal-600 py-4">
                Designs tools I used
              </h4>
              <p className="text-gray-800 dark:text-white ">Illustrator</p>
              <p className="text-gray-800 dark:text-white">Figma</p>
              <p className="text-gray-800 dark:text-white">Blender</p>
              <p className="text-gray-800 dark:text-white">Splice.com</p>
            </div>
          </div>
        </section>
        <section>
          <div className="mb-5">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-lg py-2 text-gray-800 leading-8 inline dark:text-white">
              Since I am a web developer I am fluent in
              HTML,CSS,Javascript,React,NodeJs,MongoDB. I have done internships
              at TCS and Microsoft inc. and have been on a post of
              assistant-developer at{" "}
              <span className="text-cyan-500">Google</span> also
            </p>
            <p className="text-md py-2 text-gray-800 leading-8 inline dark:text-white">
              leveling up my skills inch by inch is my goal and am never
              satisfied this is my{" "}
              <span className="text-cyan-500">resolve</span>.
            </p>
          </div>
          <div className="flex flex-col gap-6 mb-20 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-2xl hover:scale-110 transition-all ease-in-out"
                alt="web element"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-2xl hover:scale-110 transition-all ease-in-out "
                alt="web element"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-2xl hover:scale-110 transition-all ease-in-out"
                alt="web element"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-2xl hover:scale-110 transition-all ease-in-out"
                alt="web element"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-2xl hover:scale-110 transition-all ease-in-out"
                alt="web element"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-2xl hover:scale-110 transition-all ease-in-out"
                alt="web element"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
